name: workflow-test
on:
  pull_request:
    types: labeled

jobs:
  commented:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: './.github/actions/actions-test'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "test comment"
